const ACRITIQUES = {
    "SAE1.01": {
        "AC11.01": "Présenter une organisation, ses activités et son environnement (économique, sociologique, culturel, juridique, technologique, communicationnel et médiatique) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.02": "Évaluer un site web, un produit multimédia ou un dispositif interactif existant en s’appuyant sur des guides de bonnes pratiques Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.03": "Produire des analyses statistiques descriptives et les interpréter pour évaluer un contexte socio-économique Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.04": "Analyser des formes médiatiques et leur sémiotique Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.05": "Identifier les cibles (critères socio-économiques, démographiques, géographiques, culturels...) Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE1.02": {
        "AC12.03": "Proposer une recommandation marketing (cibles, objectifs, points de contact). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC12.04": "Proposer une stratégie de communication. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE1.03": {
        "AC13.02": "Produire des pistes graphiques et des planches d’inspiration. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.03": "Créer, composer et retoucher des visuels. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.06": "Optimiser les médias en fonction de leurs usages et supports de diffusion. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE1.04": {
        "AC13.01": "Ecrire pour les médias numériques. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.04": "Tourner et monter une vidéo (scénario, captation image et son...). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.06": "Optimiser les médias en fonction de leurs usages et supports de diffusion. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE1.05": {
        "AC14.01": "Exploiter de manière autonome un environnement de développement efficace et productif. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.02": "Produire des pages Web fluides incluant un balisage sémantique efficace et des interactions simples. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.03": "Générer des pages Web à partir de données structurées. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.04": "Mettre en ligne une application Web en utilisant une solution d’hébergement standard. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE1.06": {
        "AC15.01": "Gérer un projet avec une méthode classique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.02": "Budgéter un projet et suivre sa rentabilité. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.03": "Découvrir les écosystèmes d’innovation numérique (fab labs, living labs, tiers-lieux, incubateurs...). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.06": "Interagir au sein des organisations. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.07": "Produire un message écrit ou oral professionnel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE2.01": {
        "AC11.01": "Présenter une organisation, ses activités et son environnement (économique, sociologique, culturel, juridique, technologique, communicationnel et médiatique). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.03": "Produire des analyses statistiques descriptives et les interpréter pour évaluer un contexte socio-économique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC11.06": "Réaliser des entretiens utilisateurs pour construire des personae et des récits utilisateurs (user stories). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula."
    },
    "SAE2.02": {
        "AC12.01": "Concevoir un produit ou un service en terme d’usage et de fonctionnalité. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC12.02": "Construire la proposition de valeur d’un produit ou d’un service. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC12.03": "Proposer une recommandation marketing (cibles, objectifs, points de contact). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC12.04": "Proposer une stratégie de communication. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.01": "Ecrire pour les médias numériques. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.02": "Produire des pistes graphiques et des planches d’inspiration. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.03": "Créer, composer et retoucher des visuels. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.04": "Tourner et monter une vidéo (scénario, captation image et son...). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.05": "Designer une interface web (wireframes, UI). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC13.06": "Optimiser les médias en fonction de leurs usages et supports de diffusion. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.06": "Déployer et personnaliser une application Web en utilisant un CMS ou un framework MVC. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula.",
        "AC15.01": "Gérer un projet avec une méthode classique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.02": "Budgéter un projet et suivre sa rentabilité. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.03": "Découvrir les écosystèmes d’innovation numérique (fab labs, living labs, tiers-lieux, incubateurs...). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.04": "Analyser un produit ou un service innovant en identifiant les propositions de valeurs et en évaluant les solutions proposées. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.06": "Interagir au sein des organisations. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.07": "Produire un message écrit ou oral professionnel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE2.03": {
        "AC14.01": "Exploiter de manière autonome un environnement de développement efficace et productif. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.02": "Produire des pages Web fluides incluant un balisage sémantique efficace et des interactions simples. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.03": "Générer des pages Web à partir de données structurées. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.04": "Mettre en ligne une application Web en utilisant une solution d’hébergement standard. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC14.05": "Modéliser les données d’une application Web. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
    "SAE2.04": {
        "AC15.05": "Construire une présence en ligne professionnelle (personal branding). Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. ",
        "AC15.07": "Produire un message écrit ou oral professionnel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum a est sagittis, hendrerit sem et, posuere ex. Integer sodales ac mauris nec molestie. Fusce commodo nunc id quam mattis mollis. Sed a arcu id tortor tincidunt finibus in vitae diam. Sed iaculis purus in orci porttitor elementum. Fusce mauris ligula. "
    },
}